---
- name: Collect facts and configuration from devices
  hosts: AMS-test
  connection: local
  gather_facts: no
  tasks:

  ## This playbook will query facts and configuration in text format
  ## and Store the configuration in Ansible server

  - name: Collect facts and configuration from devices
    junos_facts:
      config: yes
      config_format: text
      provider: "{{ credentials }}"
    register: result

  - name: Save configuration to file in local directory
    copy: content="{{ result.ansible_facts.config }}" dest={{playbook_dir}}/{{inventory_hostname}}.conf
