---
- hosts: AMS-MX
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: get if
      junos_rpc:
        host={{ junos_host }}
        user={{ ADMUSER }}
        passwd={{ ADMPASS }}
        rpc=get-interface-information
        logfile='if.log'
        format=json
        dest=if.txt
        kwargs={interface_name:fxp0,media:True}
      register: ifinfo

    - debug: msg={{ifinfo.rpc_reply}}
