---
# probably easier with jsnapy? the below doesnt work if there are several next hops in the routing table for this destination.
- name: check if junos device learnt correctly some routes
  hosts: ex4300-4
  connection: local
  gather_facts: no

  tasks:

  - name: check if junos device learnt with BGP a route to 192.168.0.2/31 with next hop 192.168.0.3
    junos_command:
      provider: "{{  credentials }}"
      commands:
       - show route protocol bgp 192.168.0.2/31
      waitfor:
       - "result[0].route-information.route-table.rt.rt-entry.nh.to eq 192.168.0.3"
    register: junos

  - debug: var=junos.stdout[0]
  
